[ADD] 검색 기능 구현
wecode-bootcamp-korea/41-2nd-PetWithU-backend pull request #10
Opened 2023-02-02 04:22 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 키워드를 이용한 검색 기능 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- FE에서 전달한 키워드가 포함된 상품명 검색
- 해당 상품의 id, 썸네일, 상품명, 가격 리턴
- 특별한 쿼리 조건이 없으면 판매량 순으로 최대 10개 정렬하여 리스트 형태로 FE 에 전달

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="982" alt="image" src="https://user-images.githubusercontent.com/53294075/216231010-8dcb3677-ebfc-40a3-9ee3-c453f018361c.png">

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- FE 와 연결테스트를 먼저 해야 해서 테스트코드는 추후에 작성하겠습니다 😂

2023-02-02 07:09 UTC, Judy-Choi commented
conflict 해결했습니다! 🥰

2023-02-02 07:50 UTC, bigfanoftim requested changes
수정 사항과 더불어 테스트 성공 이미지도 항상 첨부해주세요!

만약 테스트 코드 작성이 어렵거나 블로커가 될 것 같다면 그 부분도 자유롭게 공유 부탁드립니다~

2023-02-02 07:50 UTC, bigfanoftim commented on src/controllers/productController.js
> +  return res.status(201).json(productListArray);
```suggestion
```
201은 created와 관련된 상태 코드이니 올바른 상태코드로 변경 부탁드려요~

2023-02-02 11:25 UTC, Judy-Choi commented on src/controllers/productController.js
> +  return res.status(201).json(productListArray);
200 으로 변경하였습니다!

저는 이 검색 기능이 상품 정보 리스트를 생성하므로(!?) 201 로 했는데, 201 은 구체적으로 뭘 생성할 때의 상태코드로 이해하면 될까요?
검색 API 는 DB 에 있는 값을 가져오는 점에 초점을 맞춰서 200 으로, 없는 토큰을 말 그대로 '생성하는' 경우에는 201을 쓰는 건가요?

2023-02-03 06:08 UTC, bigfanoftim commented on src/controllers/productController.js
> +  return res.status(201).json(productListArray);
음.. GET 요청이니 정보 리스트를 조회한다고 생각해야 합니다.
`상품 정보 리스트를 생성했다`라는 것은 단순히 변수를 생성한 것이라 그런 기준으로 response를 맞추지 않는 것이 좋겟습니다.

그리고 `201 상태코드`는 새로운 리소스를 생성한 경우, 즉 데이터가 추가된 경우라고 이해하시면 됩니다.
토큰 생성 또한 위에 말씀드린 상품 정보 리스트를 생성한 것과 같으니 201로 보기 힘들 것 같아요.

2023-02-03 06:09 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-03 06:09 UTC, merged

2023-02-03 09:51 UTC, Judy-Choi commented on src/controllers/productController.js
> +  return res.status(201).json(productListArray);
오 이해했어요 ㅎㅎ 가끔 GET 이랑 POST 도 헷갈렸는데 이 부분도 함께 해결됐습니다! 🥰