[ADD] 커뮤니티 - 게시글 등록 API 추가
wecode-bootcamp-korea/41-2nd-PetWithU-backend pull request #12
Opened 2023-02-02 11:21 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 커뮤니티 - 게시글 작성 API 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 커뮤니티 - 피드 게시글을 작성하는 API 구현
- FE 에서 nested object 형태의 데이터를 전달받아 -> 구조분해 할당 -> DB에 저장

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="722" alt="image" src="https://user-images.githubusercontent.com/53294075/216310757-92326d85-3c3d-4e88-ae8b-72016841b45f.png">

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
- community_posts
![image](https://user-images.githubusercontent.com/53294075/216311117-460ddc95-dd04-47f6-84f6-9a7adba1ea3e.png)

- community_post_details
<img width="555" alt="image" src="https://user-images.githubusercontent.com/53294075/216311195-b373c123-7601-4d98-9013-21aa5a983db0.png">

- community_image
<img width="555" alt="image" src="https://user-images.githubusercontent.com/53294075/216311246-88e43715-7f99-4550-8639-d2ec61be5b21.png">

- community_hashtags
<img width="555" alt="image" src="https://user-images.githubusercontent.com/53294075/216311310-d98e34c1-852a-4ed8-bda3-e8787afb9575.png">

<br />

## :: 기타 질문 및 특이 사항
- 테스트 코드는.. to be continued... 🥹

2023-02-03 06:13 UTC, bigfanoftim requested changes

2023-02-03 06:13 UTC, bigfanoftim commented on src/routes/communityRouter.js
> +router.post("/", validateToken, communityController.createPost);
지금 작성하신 엔드포인트 주소는 `POST :3000/community/`인데 이 주소는 커뮤니티를 생성하는 엔드포인트라고 보여지지 포스트를 생성하는 엔드포인트라고 보여지지 않습니다. `포스트를 생성하는 엔드포인트구나` 라고 생각이 들게끔 정확하게 작성해주세요.

또한 주소 마지막에는 `/`를 붙이지 말아주세요.
```suggestion
router.post("", validateToken, communityController.createPost);
```

2023-02-03 06:13 UTC, bigfanoftim commented on src/controllers/communityController.js
> +  const { postList } = req.body;
하나의 요청에 여러 게시글을 작성하는건가요?

2023-02-03 10:04 UTC, Judy-Choi commented on src/routes/communityRouter.js
> +router.post("/", validateToken, communityController.createPost);
멘토님 저도 이 부분 엔드포인트 짤 때 고민을 했는데 커뮤니티와 관련된 저희 필수 구현요소가 이렇습니다.
- 커뮤니티 피드(전체 게시글) 조회
- 커뮤니티에 글쓰기

그래서 한참 고민하다가 그냥 한가지 community 로 묶는 게 낫다고 생각했고,
CRUD 여부는 GET/POST/DELETE 로 구분 가능하다고 생각하여 단순히 POST :3000/community/ 로만 짰는데
제안해주신 피드백을 고려하면 router.post("", validateToken, communityController.createPost); 로 고치기보다는
router.post("/createpost", validateToken, communityController.createPost); 가 낫지 않을까요?

2023-02-03 10:05 UTC, Judy-Choi commented on src/controllers/communityController.js
> +  const { postList } = req.body;
넵 맞습니다 😂 저희는 하나의 게시글에 여러개의 서브 게시글이 포함됩니다!

2023-02-03 10:09 UTC, Judy-Choi commented
Conflict 해결했습니다!

2023-02-06 01:26 UTC, bigfanoftim commented on src/routes/communityRouter.js
> +router.post("/", validateToken, communityController.createPost);
POST Method에 의미가 포함되어 있으니`create`는 빼는 것이 좋겠습니다.

2023-02-06 01:27 UTC, bigfanoftim commented
질문 남겨주신 것에 대해 답변 남겼으니 확인 후 수정해 주세요

2023-02-06 01:43 UTC, Judy-Choi commented on src/routes/communityRouter.js
> +router.post("/", validateToken, communityController.createPost);
수정했습니다! 🫡

2023-02-06 02:36 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-06 02:36 UTC, merged