[ADD] 산책로 좋아요/스크랩 API
wecode-bootcamp-korea/41-2nd-PetWithU-backend pull request #20
Opened 2023-02-06 19:17 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 산책로 게시글 좋아요 / 스크랩 버튼 True/False 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 좋아요/스크랩 버튼을 클릭할 때마다 DB 테이블에 row 추가/제거되도록 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 커뮤니티에도 똑같이 쓰이는 기능을 단순 복붙하여 개발했더니 리팩토링의 필요성을 더욱 크게 느꼈습니다!
- 차라리 커뮤니티/산책로 라우터에 포함시키는 것이 아니라 likeRouter, CollectionRouter 를 따로 파는 게 나았을까요?
- 근데 라우터를 따로 팠어도 좋아요/스크랩 버튼만 누르는 건 원체 기능이 똑같아서... 차라리 인자 받아서 함수 한개로 처리하는게 나았을까요 ._.)
- 프론트에 전달되는 성공 메시지가 버튼 True/False 모두 toggle success 로 동일하다 보니 프론트에서 헷갈릴 수도 있겠다고 생각해요.
제 코드상 Dao 말고는 구별되는 메시지를 넣을 만한 부분이 없는데... 😂 아예 로직을 다르게 짜야 했던 걸까요?

2023-02-07 04:43 UTC, bigfanoftim requested changes
이 PR도 마찬가지로 이 기능만 올라온게 아니라 다른 것들이 많이 섞여 올라왔네요.

잘 정리후에 다시 푸시해주세요!

2023-02-07 05:47 UTC, Judy-Choi commented
새벽네시 코딩의 부작용인 것 같습니당.... 내가 뭘 치고 있는지 모른다...! 🤪
새벽에 올린 것 일괄 확인하겠습니다!

2023-02-07 07:55 UTC, bigfanoftim requested changes
이 PR도 아직 해결되지 않은 것 같은데 브랜치 섞어서 개발하시면 보통 이런 현상이 나타납니다.

항상 main에서만 feature를 만드시고 커밋을 관리하셔야 어디서 어떻게 문제가 생겼는지 파악하기도 쉽고 복구하기도 쉽습니다.

제가 봤을 때 복구하는게 쉽지 않을테니 필요한 코드만 다른 브랜치로 옮겨서 PR 남겨주세요!

2023-02-07 09:39 UTC, Judy-Choi commented
브랜치 새로 생성하여 코드 옮겼습니다! ㅠㅠ

2023-02-08 04:35 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-08 04:35 UTC, merged