[HELP] 이미지 업로드 API
wecode-bootcamp-korea/41-2nd-PetWithU-backend pull request #25
Opened 2023-02-07 10:54 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- S3와 multer 를 이용한 이미지 업로드

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- multer 추가

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- Postman 을 이용하여 이미지 업로드 테스트중인데 Malformed part header 에러가 납니다.
직역하면 잘못된 형식의 헤더 부분 에러라서 코드보단 Postman 설정(혹은 전송 값) 문제 같은데 도움 부탁드립니다 ㅠㅠ
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/53294075/217225722-be32c678-fd35-405c-8382-c9d21c5488a1.png">

2023-02-07 12:14 UTC, bigfanoftim commented
음.. postman 문제같은데... http 툴 문제면 insomnia 같은거 설치해서 거기도 오작동하는지 한번 확인해보시겠어요?

2023-02-07 14:04 UTC, Judy-Choi commented
오.. 멘토님 postman 문제가 맞았어요! insomnia 깔아서 하니까 됩니다 ㅎ
추가 에러가 떴는데 그건 multer 와 multer-s3 버전 차이 문제라 금방 재설치하여 해결했습니다 ㅎ

문제는 이제는 이 에러가 뜨는데요
`{
	"message": "The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature."
}`

제가 이해한 바로는 인증 해더 형태가 잘못되었다,
즉 인증 헤더에 크레덴셜, signedHeaders, 서명을 넣어줘야 하는 것 같은데
AWS ID 와 키를 벡에서 설정파일로 갖고 있기 때문에
애초에 프론트에서 백에 이미지 업로드를 보낼 때 헤더에 인증 정보를 넣을 이유가 없을 뿐더러
이렇게 하면 보안상 취약할 것 같습니다. ㅜㅜ
참고 블로그에서도 헤더에 특별한 작업을 하지 않았고요.
AWS 인증 헤더 쪽을 더 찾아봐야 할까요? 근데 이건 아닌 것 같고... ㅠㅠ 근데 에러는 인증헤더라 하고... 무한반복입니당 T_T

2023-02-08 05:36 UTC, bigfanoftim requested changes
그럼 도움 요청 라벨은 이제 의미 없는건가요?

2023-02-08 07:21 UTC, Judy-Choi commented
> 오.. 멘토님 postman 문제가 맞았어요! insomnia 깔아서 하니까 됩니다 ㅎ 추가 에러가 떴는데 그건 multer 와 multer-s3 버전 차이 문제라 금방 재설치하여 해결했습니다 ㅎ
> 
> ### 아래 이슈 해결!!! 문의사항 없습니다 😎
> `{ "message": "The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature." }`
> 
> 제가 이해한 바로는 인증 해더 형태가 잘못되었다, 즉 인증 헤더에 크레덴셜, signedHeaders, 서명을 넣어줘야 하는 것 같은데 참고 블로그에서 헤더에 특별한 작업을 하지 않았고, 다른 블로그도 비슷한 것 같아요. https://velog.io/@shitaikoto/Node-Multer-S3-aws-sdk AWS 인증 방법을 더 찾아봐야 할까요?

2023-02-08 07:21 UTC, closed without merging

2023-02-08 07:22 UTC, Judy-Choi commented
> > 오.. 멘토님 postman 문제가 맞았어요! insomnia 깔아서 하니까 됩니다 ㅎ 추가 에러가 떴는데 그건 multer 와 multer-s3 버전 차이 문제라 금방 재설치하여 해결했습니다 ㅎ
> > ### 아래 이슈 해결!!! 문의사항 없습니다 😎
> > `{ "message": "The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature." }`
> > 제가 이해한 바로는 인증 해더 형태가 잘못되었다, 즉 인증 헤더에 크레덴셜, signedHeaders, 서명을 넣어줘야 하는 것 같은데 참고 블로그에서 헤더에 특별한 작업을 하지 않았고, 다른 블로그도 비슷한 것 같아요. https://velog.io/@shitaikoto/Node-Multer-S3-aws-sdk AWS 인증 방법을 더 찾아봐야 할까요?

2023-02-08 07:23 UTC, Judy-Choi commented
멘토님 이미지 업로드 기능 feature/community-read 브랜치에 구현하고 PR 올렸으므로 이 PR 은 닫겠습니다!