[ADD] 카카오 로그인/회원가입 구현
wecode-bootcamp-korea/41-2nd-PetWithU-backend pull request #8
Opened 2023-02-01 08:02 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오 javascript API 를 이용한 로그인 및 회원가입 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- kakao AccessToken 수신
- AccessToken 을 이용해 카카오 서버로부터
- AppDataSource -> appDataSource (camel case) 로 일괄 수정

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-01 09:01 UTC, bigfanoftim requested changes

2023-02-01 09:44 UTC, Judy-Choi commented on src/services/userService.js
> +require("dotenv").config();
넵 server.js 이외의 파일에 있는 config() 는 일괄 삭제했습니다!

2023-02-01 09:54 UTC, Judy-Choi commented on src/services/userService.js
> +  const email = kakaoUserInfo.data.kakao_account.email || null;
멘토님 한참 구글링해봤는데 힌트가 좀 더 필요합니다 🥺

한참 생각해봤는데 왠지 이렇게 하나의 객체로 만들어서 이용하라는 뜻은 아닐 것 같습니다 😂
```
const userObj = {
    kakaoId : kakaoUserInfo.data.id || null,
    profileImage : kakaoUserInfo.data.properties.profile_image || null,
    nickname : kakaoUserInfo.data.properties.nickname || null,
    email : kakaoUserInfo.data.kakao_account.email || null
  }
```

2023-02-01 17:22 UTC, Judy-Choi commented
멘토님 테스트 코드 추가했습니다!

...사실 40기 코드를 복사해 와서 조금 수정했습니다 🫣🤭
그래서 내일 멘토님 뵙고 제가 이해한 걸 설명드리고 피드백 받고 싶은데 괜찮으세요? 🤓

2023-02-02 02:08 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-02 02:08 UTC, bigfanoftim commented on src/services/userService.js
> +  const email = kakaoUserInfo.data.kakao_account.email || null;
전달드린 키워드가 피드백의 전부인데 구글링을 통해 해결하지 못하셨다면 꼭 필요한 부분은 아니니 이번 PR에서는 넘어갑시다~

2023-02-02 02:09 UTC, bigfanoftim requested changes
squash 한번 진행해주세요~

2023-02-02 02:48 UTC, Judy-Choi commented
> squash 한번 진행해주세요~

멘토님 스쿼시 -> 커밋 하나로 합쳤습니다! 맛점하시고 오후에 뵙겠습니다 🥰

2023-02-02 06:33 UTC, bigfanoftim approved these changes
LGTM 👍

2023-02-02 06:33 UTC, merged